### ISSUE TITLE
Update command links for FBW guides that were moved to a new section on /docs

### ISSUE THREAD

**Issue by Valastiri** [flybywiresim/discord-bot#109]
Please reference the following PR for changes. I will post the expect links into this issue at a later time when the PR is in review state.

- https://github.com/flybywiresim/docs/pull/317

## Moved Pages

*URL Links to follow*

- A.Floor Command/Page - https://docs.flybywiresim.com/pilots-corner/advanced-guides/protections/afloor/
- Fix Info Command/Page (if there is one) - https://docs.flybywiresim.com/pilots-corner/advanced-guides/flight-planning/fixinfo/

-- See mav's comment below + just check the linked PR for the merged symbol for when actually merged

**Comment by benw202** [comment]
Thank you!

**Comment by frankkopp** [comment]
> Thank you!

will merge this today - we have redirects in place so no need to hurry or panic :)
