### ISSUE TITLE
Outdate Checklist - New Checklist available

### ISSUE THREAD

**Issue by Inaxair** [flybywiresim/discord-bot#123]
Hello,

a new checklist is available here: [Manuals/pdf/A32NX Documentation/FBW A32NX Checklist.pdf](https://github.com/flybywiresim/manuals/blob/e1a380763c653d8c3940896af104395f69c996da/pdf/A32NX%20Documentation/FBW%20A32NX%20Checklist.pdf)

Thanks!

**Comment by benw202** [comment]
Thank you! Will be updated soon.

**Comment by benw202** [comment]
@Inaxair A PR has been opened :)

Waiting on review to merge.

**Comment by tracernz** [comment]
> Hello,
> 
> a new checklist is available here: [Manuals/pdf/A32NX Documentation/FBW A32NX Checklist.pdf](https://github.com/flybywiresim/manuals/blob/e1a380763c653d8c3940896af104395f69c996da/pdf/A32NX%20Documentation/FBW%20A32NX%20Checklist.pdf)
> 
> Thanks!

That checklist is a bit out of date with the most recent recommendations from Airbus. I'll ping you on Discord later.
