### ISSUE TITLE
Transition to slash commands

### ISSUE THREAD

**Issue by NathanInnes** [flybywiresim/discord-bot#271]
Not entirely sure why we are not using the full potential of bots with slash commands... Gives a much better UI experience and is easier to use the commands.

Also gives better discord native functions.

**Comment by NathanInnes** [comment]
The support commands can remain as is but in terms of moderation or utility-based commands, it would be nicer to have them as slash commands. We can integrate both into the flow

**Comment by benw202** [comment]
Are we able to use both a regular prefix and slash one one command?

**Comment by NathanInnes** [comment]
Yup

**Comment by benw202** [comment]
Ok cool, how much of a refactor is it? I haven't looked into it too much myself.

I think we could start with the funnies category? Make that stable then go from there?

Then we can look at implementing it in the other categories if we see fit

**Comment by NathanInnes** [comment]
Starting from utilities would be a better approach. Not sure how to refactor it myself would have to look at docs

**Comment by benw202** [comment]
Okay, I will look into it more in-depth when I am back.
