### ISSUE TITLE
Missing ADIRS command

### ISSUE THREAD

**Issue by Valastiri** [flybywiresim/discord-bot#4]
Missing ADIRS command from the previous implementation. 
![image](https://user-images.githubusercontent.com/1619968/124960052-78947c00-e04e-11eb-82d3-59a3065b9c1c.png)

**Comment by davidwalschots** [comment]
ADIRU alignment waiting time depends on latitude. It can be as short as 5 minutes at the equator and 17 minutes at the poles.

**Comment by benw202** [comment]
I have created a PR for ADIRS ( #6 )

Do we think it's worth adding in about the different times? Or keep it simple with an average for the sake of troubleshooting

**Comment by davidwalschots** [comment]
@benw202 I'd probably leave out "wait about 7 mins". Just saying "It takes some time for the ADIRUs to align, you can check the remaining alignment time on the upper ECAM."

Also important to properly make the distinction between ADIRS and ADIRU. ADIRS consists of three isolated ADIRUs.

I don't know if we're also trying to increase the understanding of what things are? I.e. shouldn't we explain to the user what the ADIRS is meant to do?

**Comment by benw202** [comment]
@davidwalschots This is just re-adding the commands that were lost in the bot re-write. So I don't think it would be beneficial to explain what they do. It's just the quick '.adirs' command for when people come to us in #support. 

The docs team are working on a guide about systems that we can reference for learning when needed. (https://docs-git-fork-benw202-briefing-overhead-left-flybywire.vercel.app/a32nx-briefing/ovhd/adirs/)

**Comment by tracernz** [comment]
> It takes some time for the ADIRUs to align
Maybe "It takes several minutes for the ADIRUs to align" to give a little better idea of the time scale.

**Comment by benw202** [comment]
New PR for commands after a mishap! (#7) 

More commands have been added, any feedback on my wording would be appreciated!

**Comment by xZreai** [comment]
Checklist command is missing

**Comment by Valastiri** [comment]
I am changing the title of this issue and having @benw202 create a new tracking issue as they'll be working on this more than me. Easier for them to update the list. 

Apologies for the mild confusion.
