### ISSUE TITLE
slash command/message app translation layer

### ISSUE THREAD

**Issue by doosedev** [flybywiresim/discord-bot#407]
### Feature type

Utility or complex functionality

### Description

Feature request: Incorporate a translation layer between the existing command executors/permissions and Discord's slash command/message app API.

### Discord Username (optional)

pererry#8489

**Comment by NathanInnes** [comment]
A way to implement this would be to have moderation commands be slash commands, better usability for mods.

**Comment by benw202** [comment]
> 

Yeah, we're now changing the structure of how we're going to be doing it.

Different bots:

Moderation (Slash)

User (Our standard support bot, prefix only)

Utils (Slash to leverage the app command features for commands like metar etc etc)

**Comment by pdellaert** [comment]
Closing because implemented in discord-bot-utils
