### ISSUE TITLE
Airframe command for A32NX needs updated URL

### ISSUE THREAD

**Issue by pdellaert** [flybywiresim/discord-bot#423]
### Bug type

Wrong data or information

### Describe the bug

The Airframe command points to a place in the doc that highlights the info has moved. Bot should use the correct link as well.

### Expected behavior

Use https://docs.flybywiresim.com/fbw-a32nx/feature-guides/simbrief/#simbrief-airframe

### Steps to reproduce

1. Execute the `.airframe` command

### Discord Username (optional)

straks#7240

**Comment by benw202** [comment]
Fixed in #420
