### ISSUE TITLE
"Versions" command has outdated links

### ISSUE THREAD

**Issue by Valastiri** [flybywiresim/discord-bot#452]
### Bug type

Wrong data or information

### Describe the bug

Links in the versions command all point towards Bunny CDN. 

### Expected behavior

Should use our new cloudflare links or I believe github in the case of full downloads not from installer.

### Steps to reproduce

1. Run command on Discord.
2. Click on "Download Here"the 

### References (optional)

<img width="528" alt="image" src="https://github.com/flybywiresim/discord-bot/assets/1619968/77daeb2c-622c-4fdf-a88c-2ef5cd30fbc4">

<img width="910" alt="image" src="https://github.com/flybywiresim/discord-bot/assets/1619968/a9106231-7bf0-4363-a673-7a88220f954a">

### Discord Username (optional)

Valastiri#8902

**Comment by Valastiri** [comment]
For exp yea I guess // although I forgot the reasoning why

**Comment by benw202** [comment]
> For exp yea I guess // although I forgot the reasoning why

To discourage downloads I think?
