### ISSUE TITLE
Metar, taf and station to use the same environmental variable

### ISSUE THREAD

**Issue by Lauvaan** [flybywiresim/discord-bot#468]
### Feature type

Utility or complex functionality

### Description

Currently the taf(#467 ), metar and station commands all use different environmental variables, which all have the same value specified in the .env file. In my opinion they all could use the same variable, which would simplify documentation and deployment to devolepement enviroments.

### References (optional)

TAF_TOKENs are from #467 
![image](https://github.com/flybywiresim/discord-bot/assets/122087991/32174fcb-bf4d-4643-9041-8f4298944a2b)
![image](https://github.com/flybywiresim/discord-bot/assets/122087991/4684d88b-bd0c-4466-8aa2-e3effb292e19)

### Discord Username (optional)

Lauvaan#3330

**Comment by benw202** [comment]
We are using different tokens as this provides me more granular stats for our API usage. I can how many calls each command is using (Metar, Station or TAF). We don't have an unlimited plan with AVWX, although it is a higher call count than the free tier. See below:

![image](https://github.com/flybywiresim/discord-bot/assets/67422707/92ba33f5-bd11-4847-9761-6862b36a71e4)
