### ISSUE TITLE
Command for simbridge debug

### ISSUE THREAD

**Issue by auroraisluna** [flybywiresim/discord-bot#473]
### Feature type

Support information

### Description

A command that will show some information regarding debugging simbridge. Suggested text:
```fix
Title: Understanding why SimBridge is crashing

SimBridge will typically crash moments after it has started due to a bad installation of SimBridge, missing modules or some other issue. In order to assist you further we will need to see your SimBridge logs.

- Open the folder where SimBridge is installed
- Open a terminal window in that location (Hold `SHIFT` and right click on the empty space of the folder and select "Open Windows Terminal" or "Open Command Prompt" or "Open Powershell Window" 
- Type in `fbw-simbridge.exe` and press enter
- Screenshot the output of the console
```

Recommend image (would suggest someone else to pick one as mine is bloated) 
![image](https://github.com/flybywiresim/discord-bot/assets/98479040/979a0914-e39a-408b-abb8-7744aed0baca)

### Discord Username (optional)

alepouna

**Comment by Lauvaan** [comment]
Do you have any recommendations for aliases? Maybe `sbdebug`?
