### ISSUE TITLE
Update ProtonVPN information to accommodate for free plan changes

### ISSUE THREAD

**Issue by Kostiskat** [flybywiresim/discord-bot#523]
### Bug type

Wrong data or information

### Describe the bug

The United States is now available only with a paid subscription. I suggest removing the country specific remark on the bot message and replacing it with something more generic. Solving ECONNRESET issues seems to work just as well when connecting to other countries.

**Edit**: The United States is available in the free plan but the location you will end up with is very random since it's up to Proton to decide what's better.

### Expected behavior

Updated command information

### Steps to reproduce

N/A

### References (optional)

![image](https://github.com/flybywiresim/discord-bot/assets/80099327/bda3c891-bb3a-4d83-a97f-1a09cba127bd)
![image](https://github.com/flybywiresim/discord-bot/assets/80099327/0b6fe847-2710-4bad-a7a8-18ef2e063966)

### Discord Username (optional)

ccute

**Comment by ExampleWasTaken** [comment]
I think @LunakisDev wanted to take a look at this?

**Comment by Kostiskat** [comment]
@alepouna where is this? every VPN node under the united states is listed as available for plus members only. the only option under "free connections" is "Fastest"
![image](https://github.com/flybywiresim/discord-bot/assets/80099327/a5bbe1e4-2402-427e-a74b-8dab9afc2d8b)
all plus countries listed below require a subscription

**Comment by alepouna** [comment]
> @alepouna where is this? every VPN node under the united states is listed as available for plus members only. the only option under "free connections" is "Fastest" ![image](https://private-user-images.githubusercontent.com/80099327/334063538-a5bbe1e4-2402-427e-a74b-8dab9afc2d8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDUxNjUsIm5iZiI6MTcxNjgwNDg2NSwicGF0aCI6Ii84MDA5OTMyNy8zMzQwNjM1MzgtYTViYmUxZTQtMjQwMi00MjdlLWE3NGItOGRhYjlhZmMyZDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEwMTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MDI3MzhmZTVhZjI0OGFlZjY1YjVlM2ZmNmVkMDVjZmRjZmJlMGNmMWU0ZDJhZDU1OWMwMTcwNzI3N2ZhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ks6q0SBAa-hMa0I-WN-T-QI9DFJcW2CLfQ2DTu6teqI) all plus countries listed below require a subscription

If you use 'fastest' it gives you an option to change server and it connects you to US. If you click the tooltip for free connections, it's also listed there. 
![image](https://github.com/flybywiresim/discord-bot/assets/98479040/5fa24c15-3965-4dc5-ace3-9044942f8632)

**Comment by Kostiskat** [comment]
> If you use 'fastest' it gives you an option to change server and it connects you to US. If you click the tooltip for free connections, it's also listed there.
feels like a bit of a reach for the end user who just wants to solve an install issue especially since any country really would work

p.s. clicking on "change server" is a bit of a hit or miss since it sometimes connects me to the netherlands and sometimes to the US with no prompt to select a region

**Comment by ExampleWasTaken** [comment]
> > @alepouna where is this? every VPN node under the united states is listed as available for plus members only. the only option under "free connections" is "Fastest" ![image](https://private-user-images.githubusercontent.com/80099327/334063538-a5bbe1e4-2402-427e-a74b-8dab9afc2d8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDUxNjUsIm5iZiI6MTcxNjgwNDg2NSwicGF0aCI6Ii84MDA5OTMyNy8zMzQwNjM1MzgtYTViYmUxZTQtMjQwMi00MjdlLWE3NGItOGRhYjlhZmMyZDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEwMTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MDI3MzhmZTVhZjI0OGFlZjY1YjVlM2ZmNmVkMDVjZmRjZmJlMGNmMWU0ZDJhZDU1OWMwMTcwNzI3N2ZhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ks6q0SBAa-hMa0I-WN-T-QI9DFJcW2CLfQ2DTu6teqI) all plus countries listed below require a subscription
> 
> If you use 'fastest' it gives you an option to change server and it connects you to US. If you click the tooltip for free connections, it's also listed there. 

I cannot reproduce this behavior.

Clicking on fastest creates a new connection but the user has no control over the location.
The tooltip specifies the locations included in the free plan but does not indicates that the user has control over which location is actually used.

Additionally, this upsell indicates that custom locations are not available on the free plan:
![image](https://github.com/flybywiresim/discord-bot/assets/58574351/f3396e8b-5918-420c-9cc5-482ba2f83b10)
