### ISSUE TITLE
Add the code languages for the documentation website as well as the discord bot onto the ".dl" command

### ISSUE THREAD

**Issue by CaptCrystal** [flybywiresim/discord-bot#534]
### Feature type

General information

### Description

Adding additional code languages to the .dl command such as the documentation site, flybywiresim.com site, and the discord bot

### Additional info (optional)

If I could be assigned to this, that would be great!

### Discord Username (optional)

captcrystal

**Comment by pdellaert** [comment]
This command is no longer in use, everything has moved to the new bot and commands are now dynamically managed.
